steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/pockubernates/quickstart-image', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/pockubernates/quickstart-image:latest']
images:
- 'gcr.io/pockubernates/quickstart-image'

