steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.' ]
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'docker', '-- pull', 'gcr.io/firm-scout-200012/quickstart-image:latest' ]
images:
- 'gcr.io/$PROJECT_ID/quickstart-image'
